### ISSUE TITLE
根本就不会用，能不能把整个流程都说一下

### ISSUE THREAD

**Issue by lijicheng123** [fex-team/receiver#10]
就不能好好的做个像样的demo看看了，根本就不会用，能不能把整个流程都说一下

**Comment by oxUnd** [comment]
http://fis.baidu.com/fis3/docs/beginning/debug.html#%E5%8F%91%E5%B8%83%E5%88%B0%E8%BF%9C%E7%AB%AF%E6%9C%BA%E5%99%A8
