### ISSUE TITLE
window客户端 推送到 linux上 远端目录问题

### ISSUE THREAD

**Issue by liyanlong** [fex-team/receiver#7]
我是用的是fis3, 客户端 配置如下：

``` javascript
fis.match('*', {


    deploy: fis.plugin('http-push', {
    receiver: 'http://192.168.41.104:8999/receiver',
    //远端目录
    to: '/home/liyl/dist/fis/'
  })
})
```

使用 fis3 release  后发现. 原本的 '/' 被解析成了 '\'
![di e0h vd7jqi5sh4cafkn](https://cloud.githubusercontent.com/assets/8005864/17357222/4ce35316-598e-11e6-8091-7f6630cf1c9e.png)

**Comment by 2betop** [comment]
我马上修复下。

**Comment by 2betop** [comment]
3.4.20 修复了这个问题
